name: Label Detection
description: "Determines the new version tag based on PR labels (major, minor, patch) and outputs the label."

on:
  workflow_call:
    outputs:
      PR_LABEL:
        description: "The PR Label"
        value: ${{ jobs.label-detection.outputs.PR_LABEL }}

jobs:
  label-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures we get all tags

      - name: Get PR tag
        env:
          LABELS: ${{ toJson(github.event.pull_request.labels) }}
        run: |
          echo "PR Labels: $LABELS"
          
          if echo "$LABELS" | grep -q '"name":"major"'; then
            echo "PR_LABEL=major" >> $GITHUB_ENV
          elif echo "$LABELS" | grep -q '"name":"minor"'; then
            echo "PR_LABEL=minor" >> $GITHUB_ENV
          elif echo "$LABELS" | grep -q '"name":"patch"'; then
            echo "PR_LABEL=patch" >> $GITHUB_ENV
          else
            echo "PR_LABEL=patch" >> $GITHUB_ENV
          fi