name: Label Detection
description: "Determines the new version tag based on PR labels (major, minor, patch) and outputs the label."

on:
  workflow_call:
    outputs:
      PR_LABEL:
        description: "The PR Label"
        value: ${{ jobs.label-detection.outputs.PR_LABEL }}

jobs:
  label-detection:
    runs-on: ubuntu-latest
    outputs:
      PR_LABEL: ${{ steps.get-label.outputs.PR_LABEL }}

    steps:
      - name: Get PR Label
        id: get-label
        env:
          LABELS: ${{ toJson(github.event.pull_request.labels) }}
        run: |
          echo "PR Labels: $LABELS"

          if echo "$LABELS" | grep -q '"name":"major"'; then
            LABEL="major"
          elif echo "$LABELS" | grep -q '"name":"minor"'; then
            LABEL="minor"
          elif echo "$LABELS" | grep -q '"name":"patch"'; then
            LABEL="patch"
          else
            LABEL="patch"
          fi

          echo "PR_LABEL=$LABEL" >> $GITHUB_ENV
          echo "PR_LABEL=$LABEL" >> $GITHUB_OUTPUT  # ✅ Fixes workflow output issue
