name: Label Detection
description: "Determines the new version tag based on PR labels (major, minor, patch) and outputs the label."

on:
  workflow_call:
    outputs:
      PR_LABEL:
        description: "The PR Label"
        value: ${{ jobs.label-detection.outputs.PR_LABEL }}

jobs:
  label-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures we get all tags

      - name: Get PR tag
        run: |
          PR_LABEL=$(jq -r '.pull_request.labels[] | select(.name=="major")' <<< "${{ toJson(github.event) }}")
          if [[ "$PR_LABEL" != "" ]]; then
            echo "::set-output name=PR_LABEL::major"
          else
            PR_LABEL=$(jq -r '.pull_request.labels[] | select(.name=="minor")' <<< "${{ toJson(github.event) }}")
            if [[ "$PR_LABEL" != "" ]]; then
              echo "::set-output name=PR_LABEL::minor"
            else
              echo "::set-output name=PR_LABEL::patch"
            fi
          fi