name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        id: npm-install
        uses: actions/setup-node@v3
        with:
          node-version: 'v18'
      
      - name: Update Version
        id: version-detection
        uses: ./.github/workflows/_trunk-version-detection.yml

      - name: Tag Commit
        needs: [npm-install, version-detection]
        uses: ./.github/workflows/_tag-commit.yml
        with:
          NEW_VERSION: ${{ steps.version-detection.outputs.NEW_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Deploy
        run: echo "Deploying!"