name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  version-detection:
    name: Update Version
    uses: ./.github/workflows/_trunk-version-detection.yml

  tag-commit:
    name: Tag Commit
    needs: [npm-install,version-detection]
    uses: ./.github/workflows/_tag-commit.yml
    with:
      NEW_VERSION: ${{ needs.version-detection.outputs.NEW_VERSION }}