name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  npm-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm install

  version-detection:
    name: Update Version
    needs: [npm-install]
    uses: ./.github/workflows/_trunk-version-detection.yml

  tag-commit:
    name: Tag Commit
    needs: [npm-install,version-detection]
    uses: ./.github/workflows/_tag-commit.yml
    with:
      NEW_VERSION: ${{ needs.version-detection.outputs.NEW_VERSION }}

  build:
    runs-on: ubuntu-latest
    needs: [npm-install,version-detection, tag-commit]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        id: npm-install
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Deploy
        run: echo "Deploying ${{ needs.version-detection.outputs.NEW_VERSION }}"