name: Manual Echo Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to echo'
        required: true
        type: string

jobs:
  echo_message:
    runs-on: ubuntu-latest
    steps:
      - name: Echo input message
        run: |
          echo "Received message: ${{ github.event.inputs.message }}"