name: "Get New Version"
description: "Determines the new version tag based on PR labels (major, minor, patch) and outputs the new version."

on:
  workflow_call:
    inputs:
      labels:
        required: true
        type: string
    outputs:
      new_version:
        description: "The new version tag"
        value: ${{ jobs.calculate-version.outputs.new_version }}

jobs:
  calculate-version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.calculate-version.outputs.new_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures we get all tags

      - name: Get latest tag
        id: latest_tag
        shell: bash
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "latest_tag=$TAG" >> $GITHUB_ENV
          echo "Latest tag: $TAG"

      - name: Determine version bump type
        id: version_type
       
